### ISSUE TITLE
Body validation does not work?

### ISSUE THREAD

**Issue by juliusza** [kogosoftwarellc/express-openapi#91]
I'm trying to get validator to work on the body of this route:

```
  '/filtered':
    put:
      summary: blah
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - filtered
            properties:
              filtered:
                description: status of ssid
                type: boolean
```

here are my request parameters:
`{ uri: 'http://127.0.0.1/apiv2/filtered',
  headers:
   { 'x-api-key': 'blah' },
  json: { test: 'test' } }`

I expect openapi-express to return 400, because body should be an object with filtered prop. Yet I get 200 response. Swaggerize express worked fine with this one. Am I doing something wrong here? I'll edit this to make it more reproducible after lunch....
